# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6108ef4ce77931ad5f5afb6c22f5cc633289b2ad43352183edca9eaa8608b118a9a5e444e01ff912365995d2d173dad48f44d27ee540febd64e6f624916987d8

test:
  secret_key_base: fd5eb2eda2161f239311a9d23794e83634131921ca3619844c46f478dc8565a9c38af200e5c1bcdbed590fad61185d2dd99a407cd4067cfc169ac2b1a416f362

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
